### ISSUE TITLE
Frage zum Skript

### ISSUE THREAD

**Issue by Nastras** [nicoh88/cron_fritzbox-reboot#1]
Hey @nicoh88 kurze Frage hast du was dagegen wenn wir denn Skript Kern für den Reboot mit Telegram Push Erweiterung in eine Installationsroutine aufnehmen das automatisch ein ein systemd Timer und Service mit erstellt wird um das Skript auszuführen?

Du könntest dann ja zusätzlich hier wenn du möchtest zu dem Thread verlinken. Ich könnte dir auch mein angepasste Skript vorab zukommen lassen?

Das wäre das Tool bei dem ich es gerne einbauen würde:

http://forum.smartapfel.de/forum/thread/1303-homebridge-tool-s-zum-aktualisieren-sichern-neu-aufsetzen/

Gruß Nastra

**Comment by nicoh88** [comment]
@Nastras könnt ihr gerne tun.

**Comment by Nastras** [comment]
Super, danke dir👍
