### ISSUE TITLE
Authentifizierung nicht möglich

### ISSUE THREAD

**Issue by orangebutblue** [nicoh88/cron_fritzbox-reboot#2]
Ich bekomme beim Aufruf des Skripts immer folgende Meldung:

`<HTML><HEAD><TITLE>401 Unauthorized (ERR_NONE)</TITLE></HEAD><BODY><H1>401 Unauthorized</H1><BR>ERR_NONE<HR><B>Webserver</B> Fri, 28 Sep 2018 11:26:07 GMT</BODY></HTML>
`

Das Passwort ist richtig eingetippt (Benutzername gibt es nicht). Ich könnte mir vielleicht noch vorstellen, dass es damit zusammenhängt, dass ein '$' Zeichen im Passwort enthalten ist. Aber das Passwort wird zumindest richtig in der $FRITZPW-Variable abgespeichert (Ein echo der Variable, gibt das korrekte Passwort auf der bash aus)

**Comment by herzkerl** [comment]
Ich habe als Benutzername mal 'root' probiert und zack lief es.

**Comment by nicoh88** [comment]
b49071fa4a5e02d9d06ad2d4371717ec53d4edea
