### ISSUE TITLE
what suggest for do authentication only lan

### ISSUE THREAD

**Issue by iNullNet** [nicoh88/cron_fritzbox-reboot#4]
Hi!
I've config fritzbox for use only password if you're in lan. So `$FRITZUSER:$FRITZPW" http://$IP:49000$location` it's not great... 
Do you have somes suggests for put only a password? I've tried to do something without username but it seems not possible... (or only i don't know a good way for do it)

**Comment by thoschworks** [comment]
The script uses the TR-064 protocol. This protocols only works with user/password authentification.

But you do not have to switch the way you access your FritzBox in the lan. It is possible to add a user for TR-064 and still use password-only to access your box in the lan.

**Comment by iNullNet** [comment]
> The script uses the TR-064 protocol. This protocols only works with user/password authentification.
> 
> But you do not have to switch the way you access your FritzBox in the lan. It is possible to add a user for TR-064 and still use password-only to access your box in the lan.

oh dear... you're so right... bollicks... when i've tried i'll did a terrible mistake... i've used another ip (i've two fritzbox). 
it's works perfectly!!!
Thank you very much!!

**Comment by thoschworks** [comment]
> oh dear... you're so right... bollicks... when i've tried i'll did a terrible mistake... i've used another ip (i've two fritzbox).
> it's works perfectly!!!

S**t happens. I don't want to remember all my brilliant fails... 🤦 

If it's solved for you, then close the issue, please.

**Comment by iNullNet** [comment]
of course, forgot to do it 😛.
cheers again!
