### ISSUE TITLE
Add open source license to README.md

### ISSUE THREAD

**Issue by almai** [nicoh88/cron_fritzbox-reboot#9]
Hi @nicoh88,

I'd like to use your script to create an Alfred workflow and publish it on Github. Just to make sure that it's ok for you I would like to ask you for your permission.

If you don't care anyway it'd be even greater if you were to add an open source license (e.g. MIT) to your README.md, so everyone could immediately see that it is safe to use your code in their own projects.

Thanks in advance,
@almai

**Comment by nicoh88** [comment]
Sure. No Problem!
